import SwiftUI

struct ResultView: View {
    @ObservedObject var viewModel: QuizViewModel
    var body: some View { ScrollView { VStack(spacing: 20) { Text("📊 KẾT QUẢ").foregroundStyle(.blue).bold(); Text("Kết quả bài thi").font(.largeTitle.bold()); Text(viewModel.selectedSet?.title ?? "Farm Cert").foregroundStyle(.secondary); Text("\(viewModel.correctCount * 100 / max(1, viewModel.questions.count))%").font(.system(size: 64, weight: .bold)).foregroundStyle(viewModel.wrongCount == 0 ? .green : .red); HStack { Stat(value: "\(viewModel.correctCount)", label: "ĐÚNG", color: .green); Stat(value: "\(viewModel.wrongCount)", label: "SAI", color: .red); Stat(value: "\(max(0, viewModel.questions.count - viewModel.results.count))", label: "BỎ QUA", color: .orange) }; HStack { Button("Trang chủ") { viewModel.backHome() }.buttonStyle(.borderedProminent); Button("Tất cả câu") { viewModel.retryAll() }.buttonStyle(.bordered); Button("Làm lại sai") { viewModel.retryWrong() }.buttonStyle(.bordered).disabled(viewModel.wrongCount == 0) }; Text("Xem lại bài làm").font(.title2.bold()); ForEach(viewModel.questions.indices, id: \.self) { index in ReviewRow(index: index, question: viewModel.questions[index], correct: viewModel.results[index] == true) } }.padding() } }
}

struct Stat: View { let value: String; let label: String; let color: Color; var body: some View { VStack { Text(value).font(.title.bold()).foregroundStyle(color); Text(label).font(.caption).foregroundStyle(.secondary) }.frame(maxWidth: .infinity).padding().background(.gray.opacity(0.08), in: RoundedRectangle(cornerRadius: 12)) } }
struct ReviewRow: View { let index: Int; let question: QuizQuestion; let correct: Bool; var body: some View { HStack(alignment: .top) { Image(systemName: correct ? "checkmark.circle.fill" : "xmark.circle.fill").foregroundStyle(correct ? .green : .red); VStack(alignment: .leading) { Text("Câu \(index + 1)").bold(); Text(question.question).font(.subheadline).lineLimit(3) }; Spacer() }.padding().background((correct ? Color.green : Color.red).opacity(0.08), in: RoundedRectangle(cornerRadius: 12)) } }
